### ISSUE TITLE
It won't paste objects

### ISSUE THREAD

**Issue by Thepuppetqueen57** [ShineUA/geometrize2gd-mod-geode#1]
When I try to import a json it reads the file. I know that because it tells me how many objects the file has. But when I click convert it says that it was a succsess but it just doesn't paste any objects. What do I do? Also yes I've tried reinstalling the mod, trying different shapes, but nothing works.

**Comment by ShineUA** [comment]
> When I try to import a json it reads the file. I know that because it tells me how many objects the file has. But when I click convert it says that it was a succsess but it just doesn't paste any objects. What do I do? Also yes I've tried reinstalling the mod, trying different shapes, but nothing works.

Just read tutorial carefully.
