### ISSUE TITLE
Crash uploading json file on Android (new version) 

### ISSUE THREAD

**Issue by FakeMichi3** [ShineUA/geometrize2gd-mod-geode#4]

**Comment by ShineUA** [comment]
Can you describe the crash?

**Comment by ShineUA** [comment]
Try to update geode launcher to latest version.

**Comment by ShineUA** [comment]
I mean not the geode, but the launcher that launches gd with geode. Because I can't reproduce this bug. It just works for me.

**Comment by FakeMichi3** [comment]
> I mean not the geode, but the launcher that launches gd with geode. Because I can't reproduce this bug. It just works for me.

I have updated the launcher too, it is version 1.3.2 but I want to mention that I'm using 32 bit launcher maybe you can tell me if there's a deal with it

**Comment by ShineUA** [comment]
If this willn't help the Idk. It's maybe on geode's side.

**Comment by ShineUA** [comment]
So idk how to help you. It's works on other platforms (Android64 & Windows). Just wait for Geode Launcher updates, maybe one of this will fix your issue.
