### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by derpydepy** [ShineUA/geometrize2gd-mod-geode#5]
### Select your platform

Android32

### Describe your issue

It just doesn't work. I tried multiple times but it never works. Everytime i select a json it just crashes. Im pretty sure i got the latest verison of the mod which is 1.1.2. Btw i have the latest version of the launcher which is 1.3.2.

### Steps to reproduce the bug

1. Select an object then press the json button on the edit tab
2. Click on "select file"
3. Then if you select a json it just crashes 

### Extra fields

- [x] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.

**Comment by ShineUA** [comment]
Can you send crashlog?

**Comment by ShineUA** [comment]
cuz I don't have a android32 device

**Comment by ShineUA** [comment]
It's very hard to figure out the problem

**Comment by derpydepy** [comment]
![Screenshot_20240301-065524](https://github.com/ShineUA/geometrize2gd-mod-geode/assets/161694158/e1da4324-afd0-464c-ad32-24c0054e9819)
Here's the logs. Im assuming this is what you are referring to right?

**Comment by soggycatt** [comment]
ive been having this same problem but im 64 bit

**Comment by ShineUA** [comment]
> ![Screenshot_20240301-065524](https://github.com/ShineUA/geometrize2gd-mod-geode/assets/161694158/e1da4324-afd0-464c-ad32-24c0054e9819)
> Here's the logs. Im assuming this is what you are referring to right?

I mean crashlogs, but not the application logs.
It's located in `GEODE_DIR/game/crashlogs` send the file with latest date on it.

**Comment by Manaaos** [comment]
Hii, i'm having the same problem on Android 32, this is the latest crashlog i have, i crashed the game specifically for this lul
[Crash 2024-03-01 05.37.13.dmp](https://github.com/ShineUA/geometrize2gd-mod-geode/files/14458587/Crash.2024-03-01.05.37.13.dmp)

Not sure if this the file, i mean idk what dmp means but ig this is the one u mean.

**Comment by ZaldyColinares** [comment]
Hello, I'm also having the same issue but I guess it also affects x64 Android devices like mine

I wished it worked as it should but maybe fixes would be appreciated hehe.

![Screenshot_2024-03-03-13-44-43-49_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/ShineUA/geometrize2gd-mod-geode/assets/55983382/b201eea3-c5e6-4b17-8096-a4e3b361a258)

**Comment by ShineUA** [comment]
New update just out. It may fix your issues but I'm not sure.

**Comment by ZaldyColinares** [comment]
> New update just out. It may fix your issues but I'm not sure.

Is it pushed yet? I looked at the mod page and there were no updates still

**Comment by ShineUA** [comment]
It's already in Geode Index. But first it goes to releases page

**Comment by ShineUA** [comment]
![image](https://github.com/ShineUA/geometrize2gd-mod-geode/assets/121640980/5b1d3fb5-3533-409a-b424-c6498d824451)

**Comment by ShineUA** [comment]
or not

**Comment by ShineUA** [comment]
So, did it fixed your issues?

**Comment by Manaaos** [comment]
> So, did it fixed your issues?

Hello, yes, it's now fixed on Android32! Thank you ;)
