### ISSUE TITLE
Please make different shapes work

### ISSUE THREAD

**Issue by Nmixxnix** [ShineUA/geometrize2gd-mod-geode#6]
When I generate an image with any shape other than circles it doesn't work and just doesn't generate.
so can you please make other shapes work because they have higher resolution than circles

**Comment by ShineUA** [comment]
I think I'll add squares.

**Comment by ZaldyColinares** [comment]
Oval shapes also fitting...

**Comment by RueOfficial** [comment]
with the new 2.2 features, we can use squares, rectangles, trangles, elipses and lines, and their rotated versions too

however if its difficult to have all them working, elipses would be a must imo

**Comment by ShineUA** [comment]
> with the new 2.2 features, we can use squares, rectangles, trangles, elipses and lines, and their rotated versions too
> 
> however if its difficult to have all them working, elipses would be a must imo

yup, it's difficult to make them appear properly

**Comment by ShineUA** [comment]
circles was the easiest one

**Comment by ShineUA** [comment]
> with the new 2.2 features, we can use squares, rectangles, trangles, elipses and lines, and their rotated versions too
> 
> however if its difficult to have all them working, elipses would be a must imo

Ellipses is now done, I'm working on squares now.

**Comment by ShineUA** [comment]
Rotated ellipses also done

**Comment by ShineUA** [comment]
Well, oval shapes is done in update v1.2.0, so I think I can close this suggestion
