### ISSUE TITLE
no file explorer [BUG] 

### ISSUE THREAD

**Issue by Sweet-Fruit** [ShineUA/geometrize2gd-mod-geode#7]
### Select your platform

Windows

### Describe your issue

when i use gd from steam, when it says "select file" it doesnt open the file explorer, and i cant select my json file. [BUG] 

### Steps to reproduce the bug

- click select file in the gd editor
- doesnt open to select file

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.

**Comment by ShineUA** [comment]
Are you sure? Sometimes explorer can just open in background below geometry dash. Because it just works for me.

**Comment by PoD3Sta6108807** [comment]
> Are you sure? Sometimes explorer can just open in background below geometry dash. Because it just works for me.

no, it does not open behind. but no problem it must be my computer. btw nice mod :D

**Comment by ShineUA** [comment]
Ok, then I close the issue
