### ISSUE TITLE
[Suggestion] Button Options before generating the image in the level

### ISSUE THREAD

**Issue by LopyLuna** [ShineUA/geometrize2gd-mod-geode#8]
### Describe your suggestion

probably an option to ignore pitch black and/or white objects before generating the image in the level "basically making generating images without a background"

and also probably add buttons in this area to swap from circle to squares (basically changing the circle object to the square object) basically swapping the circle with a square instead before the generated the image in the level
![image](https://github.com/ShineUA/geometrize2gd-mod-geode/assets/100169742/ac505231-bc38-4f4b-8a15-c0a1963a97c9)

**Comment by ShineUA** [comment]
It not generates it from image, it just takes generated .json and implements it as gd objects, but only circles supported for now.

**Comment by ShineUA** [comment]
I just working at video2gd now.
