### ISSUE TITLE
Crash on create image

### ISSUE THREAD

**Issue by Konraiser** [ShineUA/geometrize2gd-mod-geode#9]
### Select your platform

Android32

### Describe your issue

When I press "create" with selected json file, the game just crash.

### Steps to reproduce the bug

1. Select json file
2. Press "create"

### Extra fields

- [X] I updated Geode to latest version.
- [X] I updated Geode Launcher (Android) to latest version.
- [X] I updated this mod to latest version.

**Comment by ShineUA** [comment]
Hello. Try to read guide carefully. If it will not help you then it's just problem with your phone/tablet I guess. There was problem with Android32 but it was fixed.
